version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://app@postgres/app
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app